name: Development Tests

on:
  pull_request:
  pull_request_review:
    types: [submitted]
  workflow_dispatch:

jobs:
  model-cache:
    name: "Model Cache"
    if: github.event_name != 'pull_request_review' || github.event.review.state == 'approved'
    uses: ./.github/workflows/model-cache.yml

  build-and-test:
    name: "Build and Test"
    needs: [model-cache]
    if: github.event_name != 'pull_request_review'
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}-build-and-test
      cancel-in-progress: true
    uses: ./.github/workflows/unit-tests.yml
    secrets: inherit
    with:
      ios-version: "27.0"
      ios-device: "iPhone 18 Pro"
      watchos-version: "27.0"
      visionos-version: "27.0"
      macos-runner: "xcode-27"
      xcode-version: "27.0"
      model-cache-key: ${{ needs.model-cache.outputs.cache-key }}

  check-approvals:
    name: "Check Approvals"
    if: github.event_name != 'pull_request_review' || github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    outputs:
      reviews: ${{ steps.reviews.outputs.state }}
    permissions:
      pull-requests: read
      contents: read
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd #v5.0.1
      - name: Check Approvals
        id: reviews
        env:
          GH_TOKEN: ${{ github.token }}
          pr: ${{ github.event.pull_request.number }}
        run: |
          echo "Checking PR approval for: $pr"
          state=$(gh pr view $pr --json reviewDecision --jq '.reviewDecision')
          echo "Review decision state: $state"
          echo "state=$state" >> "$GITHUB_OUTPUT"

  pre-merge-tests:
    name: "Pre-merge Tests"
    needs: [check-approvals, model-cache]
    if: needs.check-approvals.outputs.reviews == 'APPROVED' || github.event_name == 'workflow_dispatch'
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}-${{ matrix.os }}
      cancel-in-progress: true
    strategy:
      matrix:
        include:
          - os: macos-15
            ios-version: "18.5"
            ios-device: "iPhone 16"
            watchos-version: "11.5"
            visionos-version: "2.5"
            xcode-version: "16.4"
          - os: macos-26
            ios-version: "26.5"
            ios-device: "iPhone 17"
            watchos-version: "26.5"
            visionos-version: "latest"
            xcode-version: "26.6"
    uses: ./.github/workflows/unit-tests.yml
    secrets: inherit
    with:
      macos-runner: ${{ matrix.os }}
      ios-version: ${{ matrix.ios-version }}
      ios-device: ${{ matrix.ios-device }}
      watchos-version: ${{ matrix.watchos-version }}
      visionos-version: ${{ matrix.visionos-version }}
      xcode-version: ${{ matrix.xcode-version }}
      model-cache-key: ${{ needs.model-cache.outputs.cache-key }}
